### ISSUE TITLE
How add regex profile for hi type subs

### ISSUE THREAD

**Issue by hlugt** [KBlixt/subcleaner#40] opened 2023-05-05 10:22 UTC
Hi, thanks for this subcleaner.

Can you please explain how to add hearing-impaired subs to the regex language profile? 
Bazarr puts them like "<name>.en.hi.srt". 
Running subcleaner give a warning: "WARNING: language 'hi' have no regex profile associated with it."
Should/Can it be added as a language code en.hi in de english regex profile conf? 
I get the idea it looks at id it as a separate language...

**Comment by KBlixt** [comment] 2023-05-05 10:51
ah, nice catch, this is a bug.

**Comment by KBlixt** [comment] 2023-05-05 11:12
could you send me the entire filename where you encounter this and the command you use?

Thank you :)

**Comment by hlugt** [comment] 2023-06-23 10:01
Oops, my apologies: had not seen the request for filename and command...

**Comment by KBlixt** [comment] 2023-06-23 10:20
No problem, I closed it since I can't reproduce it, so maybe it's been fixed as a side effect of something else I did. But would be great if you could confirm that this isn't a problem anymore 🙂

**Comment by hlugt** [comment] 2023-06-23 16:19
Ok, I must admit, I am not sure anymore how I stumbled across this issue. I think it is probably resolved, as I can see the following in the log:
2023-06-05_22:55:32 -     INFO: now cleaning subtitle: /data/movies/New/Doctor Strange in the Multiverse of Madness (2022)/Doctor.Strange.in.the.Multiverse.of.Madness.2022.2160p.UHD.BluRay.HDR10.REMUX.HEVC.TrueHD.7.1.Atmos-UnKn0wn {imdb-tt9419884}.en.hi.srt

**Comment by saaiborg** [comment] 2023-11-05 17:17
Hi,

I'm having the same issue, but the hearing-impaired subs are marked as nameofthecontent.en.**sdh**.srt
So "sdh" instead of "hi"

The error I get:

BAZARR Post-processing result for file /media/******.mkv : WARNING: language 'sdh' have no regex profile associated with it. WARNING: either create a regex profile for it or disable require_language_profile in the config. ERROR: subcleaner didn't successfully clean any files, failed to clean 1 files. subcleaner didn't successfully clean any files, failed to clean 1 files. 

Thanks in advance for your help!

**Comment by KBlixt** [comment] 2023-11-05 20:48
@saaiborg
Thank you for letting me know, I made a quick fix for this. Give it a try again and let me know if it works 🙂

**Comment by saaiborg** [comment] 2023-11-05 21:42
> @saaiborg Thank you for letting me know, I made a quick fix for this. Give it a try again and let me know if it works 🙂

Great! It works.
Many thanks for your great work

**Closed** 2023-11-06 07:00 UTC
